In [2]:
import torch
import numpy as np

A torch tensor can be initialized from a list, a numpy array, a tuple, a float, or any iterable. 

In [5]:
w = torch.tensor(1.3)
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.tensor(np.array([1, 2, 3, 4])) 
z = torch.tensor(range(18))
print(w)
print(x) 
print(y) 
print(z)

tensor(1.3000)
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])


We can access its `dtype` and its shape with the following attributes/methods.

In [6]:
print(x.dtype) 
print(x.shape) 
print(x.size())
print(x.dim())

torch.int64
torch.Size([3, 3])
torch.Size([3, 3])
2


Note that `torch.tensor` infers the `dtype` while `torch.Tensor` uses `torch.float64`. To generate random numbers, we do the following. `

In [7]:
x = torch.randn((2, 2, 3)) # random normal distribution 
jprint(x)

tensor([[[ 0.7887,  0.1853,  0.9412],
         [-0.4127,  1.1099,  0.3560]],

        [[ 2.4980,  0.2225,  1.2892],
         [ 0.4702,  1.1336,  1.3040]]])


Given some shape, we may want to reshape it in some way. To simply swap two dimensions, we can do `transpose`, but for more general reshapes we can do multiple things. 

1. `view` is the original method that simply creates a new instance of pointers and does not copy the values. All elements of the new tensor are copied by reference.
2. `clone` simply clones the new tensor. 
3. `reshape` tries to call `view` if possible, otherwise it clones and then reshapes it. 


In [9]:
# changes the index 1 and 2 dimensions (2, 2, 3) -> (2, 3, 2) 
print(x.transpose(1, 2))

# -1 is inferred to be 3
print(x.reshape(4, 1, -1))

print(x.view(4, -1))

x_ = x.clone()
print(x_)

tensor([[[ 0.7887, -0.4127],
         [ 0.1853,  1.1099],
         [ 0.9412,  0.3560]],

        [[ 2.4980,  0.4702],
         [ 0.2225,  1.1336],
         [ 1.2892,  1.3040]]])
tensor([[[ 0.7887,  0.1853,  0.9412]],

        [[-0.4127,  1.1099,  0.3560]],

        [[ 2.4980,  0.2225,  1.2892]],

        [[ 0.4702,  1.1336,  1.3040]]])
tensor([[ 0.7887,  0.1853,  0.9412],
        [-0.4127,  1.1099,  0.3560],
        [ 2.4980,  0.2225,  1.2892],
        [ 0.4702,  1.1336,  1.3040]])
tensor([[[ 0.7887,  0.1853,  0.9412],
         [-0.4127,  1.1099,  0.3560]],

        [[ 2.4980,  0.2225,  1.2892],
         [ 0.4702,  1.1336,  1.3040]]])


Pytorch provides a lot of functionality to work with tensors. For example, `torch.chunk` divides a tensor into equally sized chunks across a dimension. 

In [13]:
x = torch.randn((5, 10, 12)) 
a1, a2, a3, a4, a5 = torch.chunk(x, 5, dim=0)
b1, b2 = torch.chunk(x, 2, dim=1)
c1, c2, c3 = torch.chunk(x, 3, dim=2)
print(a1.shape)
print(b1.shape)
print(c1.shape)

torch.Size([1, 10, 12])
torch.Size([5, 5, 12])
torch.Size([5, 10, 4])
